SET(CMAKE_INCLUDE_PATH ${OE_LIB_DIR}/FreeImage/include)
SET(CMAKE_LIBRARY_PATH ${OE_LIB_DIR}/FreeImage/lib)
INCLUDE(${OE_CURRENT_EXTENSION_DIR}/FindFreeImage.cmake)

INCLUDE_DIRECTORIES(
  ${FREEIMAGE_INCLUDE_DIR}
)
