SET(CMAKE_INCLUDE_PATH ${OE_LIB_DIR}/FreeImage/Source)
SET(CMAKE_LIBRARY_PATH ${OE_LIB_DIR}/FreeImage)
INCLUDE(${OE_CURRENT_EXTENSION_DIR}/FindFreeImage.cmake)

INCLUDE_DIRECTORIES(
  ${FREEIMAGE_INCLUDE_DIR}
)
